name: Daily Amazon Scraper

on:
  schedule:
    - cron: '30 2 * * *'  # Runs every day at 9:00 UTC
  workflow_dispatch:      # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Script
        run: python main.py
